/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qldt.View;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import qldt.Controller.AddNewTopicController;
import qldt.Controller.MenuController;
import static qldt.Controller.MenuController.menuController_GroupTopic;
import qldt.Model.GroupTopic;
import qldt.Model.Topic;
import static qldt.View.ListStudentNoGroup_AddNewTopic_View.ListStudentNoGroup_AddNewTopic_View_Student_Selected;

/**
 *
 * @author ziplo
 */
public class AddNewTopicView extends javax.swing.JFrame {

    public AddNewTopicController addNewTopicController = new AddNewTopicController();
    public static GroupTopic groupTopic = MenuController.menuController_GroupTopic;

    /**
     * Creates new form AddNewTopicView
     */
    public AddNewTopicView() {

        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new java.awt.Color(255, 255, 255));
        showInfoNewtopic();
        ImageIcon iconGroup = new ImageIcon("C:\\Users\\ziplo\\Projects\\NetBeansProjects\\QLDT\\src\\qldt\\Image\\iconTopic.png");
        jLabelnewTopic.setIcon(iconGroup);
        jLabelnewTopic.setHorizontalTextPosition(SwingConstants.RIGHT);
        jLabelnewTopic.setHorizontalAlignment(SwingConstants.LEFT);

        ImageIcon iconAdd = new ImageIcon("C:\\Users\\ziplo\\Projects\\NetBeansProjects\\QLDT\\src\\qldt\\Image\\Add.png");
        jButtonAdd.setIcon(iconAdd);
        jButtonAdd.setHorizontalTextPosition(SwingConstants.RIGHT);
        jButtonAdd.setHorizontalAlignment(SwingConstants.LEFT);

        ImageIcon iconCacel = new ImageIcon("C:\\Users\\ziplo\\Projects\\NetBeansProjects\\QLDT\\src\\qldt\\Image\\iconDelete.png");
        jButtonCancel.setIcon(iconCacel);
        jButtonCancel.setHorizontalTextPosition(SwingConstants.RIGHT);
        jButtonCancel.setHorizontalAlignment(SwingConstants.LEFT);
    }

    public void showInfoNewtopic() {
        jTextFieldTopicName.setText(MenuView.menuView_AddNewTopicView_topic.getTopicName());
        jTextFieldInstructor.setText(MenuView.menuView_AddNewTopicView_topic.getInstructor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelnewTopic = new javax.swing.JLabel();
        jTextFieldTopicName = new javax.swing.JTextField();
        jTextFieldInstructor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonAddStudent = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabelnewTopic.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelnewTopic.setForeground(new java.awt.Color(0, 153, 51));
        jLabelnewTopic.setText("Đề tài mới");

        jTextFieldTopicName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tên đề tài", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        jTextFieldInstructor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Người hướng dẫn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Thêm thành viên:");

        jButtonAddStudent.setBackground(new java.awt.Color(255, 153, 153));
        jButtonAddStudent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAddStudent.setText("Chọn sinh viên");
        jButtonAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddStudentActionPerformed(evt);
            }
        });

        jButtonAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(0, 153, 51));
        jButtonAdd.setText("Tạo");
        jButtonAdd.setContentAreaFilled(false);
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabelMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMessage.setForeground(new java.awt.Color(255, 0, 0));
        jLabelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(255, 51, 0));
        jButtonCancel.setText("Hủy");
        jButtonCancel.setContentAreaFilled(false);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonAddStudent))
                                    .addComponent(jTextFieldTopicName, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelnewTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelnewTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTopicName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        String topicName = jTextFieldTopicName.getText();
        String instructor = jTextFieldInstructor.getText();
        int checkTopicName = new AddNewTopicController().checkTopicName(jTextFieldTopicName.getText());
        if (topicName.trim().equals("") || instructor.trim().equals("")) {
            jLabelMessage.setText("Vui lòng nhập đầy đủ thông tin");
        } else if (checkTopicName == 1) {
            jLabelMessage.setText("Tên đề tài đã tồn tại");
        } else if (ListStudentNoGroup_AddNewTopic_View.ListStudentNoGroup_AddNewTopic_View_Student_Selected == 0) {
            //boolean checkDeleteFinished = addNewTopicController.cancelCreateNewTopic(new MenuController().getNewTopic().getTopicName());
            jLabelMessage.setText("Vui lòng chọn thành viên");

        } else if (ListStudentNoGroup_AddNewTopic_View.ListStudentNoGroup_AddNewTopic_View_Student_Selected == 0) {
            //boolean checkDeleteFinished = addNewTopicController.cancelCreateNewTopic(new MenuController().getNewTopic().getTopicName());
            jLabelMessage.setText("Vui lòng chọn thành viên");
        }else {
            Topic topic = new Topic(jTextFieldTopicName.getText(), jTextFieldInstructor.getText());
            Topic topic1 = new MenuController().getNewTopic();
            System.out.println(topic);
            System.out.println(jTextFieldTopicName.getText() +  jTextFieldInstructor.getText());
            boolean checkUpdate  = new AddNewTopicController().UpdateInfoTopic(topic,topic1.getTopicID() );
            if (checkUpdate == true){
                this.setVisible(false);
                JOptionPane.showMessageDialog(this, "Thêm đề tài " + jTextFieldTopicName.getText() + " thành công =))" );
            }
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddStudentActionPerformed
        new ListStudentNoGroup_AddNewTopic_View().setVisible(true);
    }//GEN-LAST:event_jButtonAddStudentActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // set GroupID cua sinh ve null

        boolean checkDeleteFinished = addNewTopicController.cancelCreateNewTopic(new MenuController().getNewTopic().getTopicName());
        if (checkDeleteFinished == true) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewTopicView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewTopicView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewTopicView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewTopicView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewTopicView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddStudent;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelnewTopic;
    private javax.swing.JTextField jTextFieldInstructor;
    private javax.swing.JTextField jTextFieldTopicName;
    // End of variables declaration//GEN-END:variables
}
