/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qldt.View;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import qldt.Controller.ListStudentNoGroupController;
import qldt.Controller.MenuController;
import qldt.Model.Student;
import qldt.Model.Topic;
import static qldt.View.MenuView.menuView_GroupTopicView_Topic;

/**
 *
 * @author ziplo
 */
public class ListStudentNoGroupView extends javax.swing.JFrame {
    public int studentIDTemp = -1;
    public String studentNameTemp = "";
    /**
     * Creates new form ListStudentNoGroupView
     */
    public ListStudentNoGroupView() {
        System.out.println("ListStudentNoGroupView--------------------");
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(255, 255, 255));
        this.setLocationRelativeTo(null);
//        ImageIcon iconDelete = new ImageIcon("C:\\Users\\ziplo\\Projects\\NetBeansProjects\\QLDT\\src\\qldt\\Image\\iconDelete.png");
//        jButtonDelete.setIcon(iconDelete);
        ImageIcon iconAdd = new ImageIcon("C:\\Users\\ziplo\\Projects\\NetBeansProjects\\QLDT\\src\\qldt\\Image\\Add.png");
        jButtonAdd.setIcon(iconAdd);
        
        jButtonAdd.setHorizontalTextPosition(SwingConstants.RIGHT);
        jButtonAdd.setHorizontalAlignment(SwingConstants.LEFT);
        showListStudent();
    }
        public void showListStudent(){
        DefaultTableModel model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false; // Tắt chức năng chỉnh sửa cho tất cả các ô
            }
        };
        jTableStudent.getTableHeader().addMouseListener(new MouseAdapter(){
            @Override
            public void mouseEntered(MouseEvent e) {
                jTableStudent.getTableHeader().setReorderingAllowed(false);
            }
        });
//       jTableStudent.addMouseListener(new MouseAdapter(){
//           public void mouseClicked(MouseEvent e) {
//               if (e.getClickCount() == 2){
//                    
//                     // new GroupTopicView().setVisible(true);
//                    
//               }
//           }
//       });
       jTableStudent.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    studentIDTemp = Integer.parseInt(String.valueOf(jTableStudent.getValueAt(jTableStudent.getSelectedRow(), 1))) ;
                    studentNameTemp = String.valueOf(jTableStudent.getValueAt(jTableStudent.getSelectedRow(), 2)) ;
                     
                }
            }
        });
       
        model.setColumnIdentifiers(new Object[]{"STT", "Mã sinh viên", "Họ và tên", "Trạng thái"});
        ArrayList<Student> students = new ListStudentNoGroupController().showList();
        System.out.println("------------------");
        int i = 1;
        for(Student student: students){
            model.addRow(new Object[]{i++,student.getStudentID(), student.getStudentName(),student.getStatus()});
        }
        jTableStudent.setModel(model);
        System.out.println("---------------------");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sinh viên", "Họ và tên"
            }
        ));
        jScrollPane1.setViewportView(jTableStudent);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Danh sách sinh viên");

        jButtonAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(0, 153, 51));
        jButtonAdd.setText("Thêm");
        jButtonAdd.setContentAreaFilled(false);
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed

        if (studentIDTemp == -1)
            JOptionPane.showMessageDialog(this, "Hãy chọn sinh viên cần thêm");
        else{
            boolean checkUpdate = new ListStudentNoGroupController().addGrouptoStudentByGroupName(MenuView.menuView_GroupTopicView_Topic.getGroupName(), studentIDTemp);
            if (checkUpdate == true){
                this.setVisible(false);
                JOptionPane.showMessageDialog(this, studentNameTemp + " đã được thêm vào nhóm" + MenuView.menuView_GroupTopicView_Topic.getGroupName());
            }
        }
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListStudentNoGroupView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListStudentNoGroupView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListStudentNoGroupView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListStudentNoGroupView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListStudentNoGroupView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStudent;
    // End of variables declaration//GEN-END:variables
}
